CREATE TABLE PAIS (
PAIS_CODIGO NUMBER(18) PRIMARY KEY,
PAIS_NOME VARCHAR2(255) NOT NULL);

CREATE SEQUENCE SEQ_PAIS
START WITH 1
INCREMENT BY 1;

INSERT INTO PAIS (PAIS_CODIGO, PAIS_NOME) VALUES (SEQ_PAIS.NEXTVAL, 'BRASIL');

CREATE TABLE ESTADO (
EST_CODIGO NUMBER(18) PRIMARY KEY,
EST_NOME VARCHAR2(255) NOT NULL,
EST_SIGLA VARCHAR2(2) NOT NULL,
EST_PAIS_CODIGO NUMBER(18),
CONSTRAINT FK_PAIS_ESTADO FOREIGN KEY (EST_PAIS_CODIGO) REFERENCES PAIS (PAIS_CODIGO));

CREATE SEQUENCE SEQ_ESTADO
START WITH 1
INCREMENT BY 1;

INSERT INTO ESTADO (EST_CODIGO, EST_NOME, EST_SIGLA, EST_PAIS_CODIGO) VALUES (SEQ_ESTADO.NEXTVAL, 'SANTA CATARINA', 'SC', 1);
INSERT INTO ESTADO (EST_CODIGO, EST_NOME, EST_SIGLA, EST_PAIS_CODIGO) VALUES (SEQ_ESTADO.NEXTVAL, 'PARANA', 'PR', 1);
INSERT INTO ESTADO (EST_CODIGO, EST_NOME, EST_SIGLA, EST_PAIS_CODIGO) VALUES (SEQ_ESTADO.NEXTVAL, 'RIO GRANDE DO SUL', 'RS', 1);
INSERT INTO ESTADO (EST_CODIGO, EST_NOME, EST_SIGLA, EST_PAIS_CODIGO) VALUES (SEQ_ESTADO.NEXTVAL, 'SÃO PAULO', 'SP', 1);
INSERT INTO ESTADO (EST_CODIGO, EST_NOME, EST_SIGLA, EST_PAIS_CODIGO) VALUES (SEQ_ESTADO.NEXTVAL, 'RIO DE JANEIRO', 'RJ', 1);

CREATE TABLE CIDADE (
CID_CODIGO NUMBER(18) PRIMARY KEY,
CID_NOME VARCHAR2(255) NOT NULL,
CID_EST_CODIGO NUMBER(18),
CONSTRAINT FK_ESTADO_CIDADE FOREIGN KEY (CID_EST_CODIGO) REFERENCES ESTADO (EST_CODIGO));

CREATE SEQUENCE SEQ_CIDADE
START WITH 1
INCREMENT BY 1;

INSERT INTO CIDADE (CID_CODIGO, CID_NOME, CID_EST_CODIGO) VALUES (SEQ_CIDADE.NEXTVAL, 'RIO DE JANEIRO', 5);
INSERT INTO CIDADE (CID_CODIGO, CID_NOME, CID_EST_CODIGO) VALUES (SEQ_CIDADE.NEXTVAL, 'SÃO PAULO', 4);
INSERT INTO CIDADE (CID_CODIGO, CID_NOME, CID_EST_CODIGO) VALUES (SEQ_CIDADE.NEXTVAL, 'PORTO ALEGRE', 3);
INSERT INTO CIDADE (CID_CODIGO, CID_NOME, CID_EST_CODIGO) VALUES (SEQ_CIDADE.NEXTVAL, 'CURITIBA', 2);
INSERT INTO CIDADE (CID_CODIGO, CID_NOME, CID_EST_CODIGO) VALUES (SEQ_CIDADE.NEXTVAL, 'BLUMENAU', 1);

CREATE TABLE ENDERECO (
END_CODIGO NUMBER(18) PRIMARY KEY,
END_TIPO_DE_LOUGRADOURO VARCHAR2(255) NOT NULL,
END_RUA VARCHAR2(255) NOT NULL,
END_RUA_NUMERO VARCHAR2(255) NOT NULL,
END_COMPLEMENTO VARCHAR2(255),
END_CEP VARCHAR2(255),
END_BAIRRO VARCHAR2(255),
END_CID_CODIGO NUMBER(18),
CONSTRAINT FK_CIDADE_ENDERECO FOREIGN KEY (END_CID_CODIGO) REFERENCES CIDADE (CID_CODIGO));

CREATE SEQUENCE SEQ_ENDERECO
START WITH 1
INCREMENT BY 1;

INSERT INTO ENDERECO (END_CODIGO, END_TIPO_DE_LOUGRADOURO, END_RUA, END_RUA_NUMERO, END_COMPLEMENTO, END_CEP, END_BAIRRO, END_CID_CODIGO) 
VALUES (SEQ_ENDERECO.NEXTVAL, 'RUA', 'A', 15, 'CASA', '89563-620', 'VILA UM', 1);
INSERT INTO ENDERECO (END_CODIGO, END_TIPO_DE_LOUGRADOURO, END_RUA, END_RUA_NUMERO, END_COMPLEMENTO, END_CEP, END_BAIRRO, END_CID_CODIGO) 
VALUES (SEQ_ENDERECO.NEXTVAL, 'RUA', 'B', 22, 'BLOCO 3 - AP 5', '56894-225', 'VILA MARIA', 2);
INSERT INTO ENDERECO (END_CODIGO, END_TIPO_DE_LOUGRADOURO, END_RUA, END_RUA_NUMERO, END_COMPLEMENTO, END_CEP, END_BAIRRO, END_CID_CODIGO) 
VALUES (SEQ_ENDERECO.NEXTVAL, 'AVENIDA', 'ATLANTICO', 105, 'CASA', '56489-635', 'VILA PRUDENTE', 3);
INSERT INTO ENDERECO (END_CODIGO, END_TIPO_DE_LOUGRADOURO, END_RUA, END_RUA_NUMERO, END_COMPLEMENTO, END_CEP, END_BAIRRO, END_CID_CODIGO) 
VALUES (SEQ_ENDERECO.NEXTVAL, 'RUA', 'SKYWALKER', 158, 'CASA', '56846-905', 'VILA SETE', 4);
INSERT INTO ENDERECO (END_CODIGO, END_TIPO_DE_LOUGRADOURO, END_RUA, END_RUA_NUMERO, END_COMPLEMENTO, END_CEP, END_BAIRRO, END_CID_CODIGO) 
VALUES (SEQ_ENDERECO.NEXTVAL, 'RUA', 'STARK', 2564, 'CASA', '86459-520', 'VILA MARVEL', 5);
INSERT INTO ENDERECO (END_CODIGO, END_TIPO_DE_LOUGRADOURO, END_RUA, END_RUA_NUMERO, END_COMPLEMENTO, END_CEP, END_BAIRRO, END_CID_CODIGO) 
VALUES (SEQ_ENDERECO.NEXTVAL, 'RUA', 'BRASIL', 171, 'CASA', '45689-253', 'CENTRO', 5);
INSERT INTO ENDERECO (END_CODIGO, END_TIPO_DE_LOUGRADOURO, END_RUA, END_RUA_NUMERO, END_COMPLEMENTO, END_CEP, END_BAIRRO, END_CID_CODIGO) 
VALUES (SEQ_ENDERECO.NEXTVAL, 'RUA', 'WAYNE', 54, 'CASA', '56846-652', 'VILA GOTHAM', 5);

CREATE TABLE TIPO_FORNECEDOR (
TIPF_CODIGO NUMBER(18) PRIMARY KEY,
TIPF_NOME VARCHAR2(255) NOT NULL);

CREATE SEQUENCE SEQ_TIPO_FORNECEDOR
START WITH 1
INCREMENT BY 1;

INSERT INTO TIPO_FORNECEDOR (TIPF_CODIGO, TIPF_NOME) VALUES (SEQ_TIPO_FORNECEDOR.NEXTVAL, 'SHAMPOO');
INSERT INTO TIPO_FORNECEDOR (TIPF_CODIGO, TIPF_NOME) VALUES (SEQ_TIPO_FORNECEDOR.NEXTVAL, 'CONDICIONADOR');


CREATE TABLE TIPO_CLIENTE (
TIPC_CODIGO NUMBER(18) PRIMARY KEY,
TIPC_NOME VARCHAR2(255) NOT NULL);

CREATE SEQUENCE SEQ_TIPO_CLIENTE
START WITH 1
INCREMENT BY 1;

INSERT INTO TIPO_CLIENTE (TIPC_CODIGO, TIPC_NOME) VALUES (SEQ_TIPO_CLIENTE.NEXTVAL, 'PADRÃO');

CREATE TABLE FORNECEDOR (
FOR_CODIGO NUMBER(18) PRIMARY KEY,
FOR_NOME VARCHAR2(255) NOT NULL,
FOR_CONTATO VARCHAR2(255),
FOR_CNPJ VARCHAR2(14),
FOR_TELEFONE VARCHAR2(15),
FOR_CELULAR VARCHAR2(15),
FOR_EMAIL VARCHAR2(255),
FOR_TIPF_CODIGO NUMBER(18),
FOR_END_CODIGO NUMBER(18),
CONSTRAINT FK_TIPF_FORNECEDOR FOREIGN KEY (FOR_TIPF_CODIGO) REFERENCES TIPO_FORNECEDOR (TIPF_CODIGO),
CONSTRAINT FK_ENDERECO_FORNECEDOR FOREIGN KEY (FOR_END_CODIGO) REFERENCES ENDERECO (END_CODIGO));

CREATE SEQUENCE SEQ_FORNECEDOR
START WITH 1
INCREMENT BY 1;

INSERT INTO FORNECEDOR(FOR_CODIGO, FOR_NOME, FOR_CONTATO, FOR_CNPJ, FOR_TELEFONE, FOR_CELULAR, FOR_EMAIL, FOR_TIPF_CODIGO, FOR_END_CODIGO)
VALUES (SEQ_FORNECEDOR.NEXTVAL, 'FORNECEDOR A', 'GUSTAVO SOUZA', '0000000111555', '(21) 4578-6852', '(21) 98578-6852', 'GUSTAVO@FORNECEDORA.COM.BR', 1, 1);
INSERT INTO FORNECEDOR(FOR_CODIGO, FOR_NOME, FOR_CONTATO, FOR_CNPJ, FOR_TELEFONE, FOR_CELULAR, FOR_EMAIL, FOR_TIPF_CODIGO, FOR_END_CODIGO)
VALUES (SEQ_FORNECEDOR.NEXTVAL, 'FORNECEDOR B', 'MARIA LIMA', '000000457785', '(11) 4054-6851', '(21) 98659-5847', 'MARIA@FORNECEDORB.COM.BR', 2, 2);

CREATE TABLE CLIENTE (
CLI_CODIGO NUMBER(18) PRIMARY KEY,
CLI_NOME VARCHAR(255) NOT NULL,
CLI_SOBRENOME VARCHAR2(255),
CLI_CPF VARCHAR2(11),
CLI_TELEFONE VARCHAR2(255),
CLI_CELULAR VARCHAR2(255),
CLI_EMAIL VARCHAR2(255),
CLI_DATA_NASCIMENTO DATE,
CLI_SEXO CHAR(1) NOT NULL,
CLI_PROFISSAO VARCHAR2(255),
CLI_PAI_MAE NUMBER(1),
CLI_TIPC_CODIGO NUMBER(18),
CLI_END_CODIGO NUMBER(18),
CONSTRAINT FK_TIPC_CLIENTE FOREIGN KEY (CLI_TIPC_CODIGO) REFERENCES TIPO_CLIENTE (TIPC_CODIGO),
CONSTRAINT FK_ENDERECO_CLIENTE FOREIGN KEY (CLI_END_CODIGO) REFERENCES ENDERECO (END_CODIGO));

CREATE SEQUENCE SEQ_CLIENTE
START WITH 1
INCREMENT BY 1;

INSERT INTO CLIENTE (CLI_CODIGO, CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_TELEFONE, CLI_CELULAR, CLI_EMAIL, CLI_DATA_NASCIMENTO, CLI_SEXO, CLI_PROFISSAO, CLI_PAI_MAE, CLI_TIPC_CODIGO, CLI_END_CODIGO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'MARIA', 'DAS DORES', '89454868556', '(47) 3033-5689', '(47) 98547-5689', 'MARIA@GMAIL.COM', TO_DATE('31/05/1985', 'DD/MM/YYYY'), 'F', 'VENDEDORA', 1, 1, 5);
INSERT INTO CLIENTE (CLI_CODIGO, CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_TELEFONE, CLI_CELULAR, CLI_EMAIL, CLI_DATA_NASCIMENTO, CLI_SEXO, CLI_PROFISSAO, CLI_PAI_MAE, CLI_TIPC_CODIGO, CLI_END_CODIGO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'MARLI', 'APARECIDA', '58668568556', '(47) 3033-5869', '(47) 98652-5864', 'MARLI@GMAIL.COM', TO_DATE('05/07/1982', 'DD/MM/YYYY'), 'F', 'PROFESSORA', 1, 1, 6);
INSERT INTO CLIENTE (CLI_CODIGO, CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_TELEFONE, CLI_CELULAR, CLI_EMAIL, CLI_DATA_NASCIMENTO, CLI_SEXO, CLI_PROFISSAO, CLI_PAI_MAE, CLI_TIPC_CODIGO, CLI_END_CODIGO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'MARCOS', 'SOARES', '58645899665', '(47) 3033-6859', '(47) 98645-5236', 'MARCOS@GMAIL.COM', TO_DATE('02/11/1992', 'DD/MM/YYYY'), 'M', 'AUXILIAR ADMINISTRATIVO', 1, 1, 4);
INSERT INTO CLIENTE (CLI_CODIGO, CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_TELEFONE, CLI_CELULAR, CLI_EMAIL, CLI_DATA_NASCIMENTO, CLI_SEXO, CLI_PROFISSAO, CLI_PAI_MAE, CLI_TIPC_CODIGO, CLI_END_CODIGO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'JULIA', 'SOUZA', '45468978951', '(47) 3033-5623', '(47) 98686-5869', 'JULIA@GMAIL.COM', TO_DATE('02/11/1992', 'DD/MM/YYYY'), 'F', 'MANICURE', 1, 1, 3);
INSERT INTO CLIENTE (CLI_CODIGO, CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_TELEFONE, CLI_CELULAR, CLI_EMAIL, CLI_DATA_NASCIMENTO, CLI_SEXO, CLI_PROFISSAO, CLI_PAI_MAE, CLI_TIPC_CODIGO, CLI_END_CODIGO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'JOÃO', 'DAS NEVES', '56874982563', '(47) 3033-5689', '(47) 98645-8475', 'JOAONEVES@GMAIL.COM', TO_DATE('02/08/1992', 'DD/MM/YYYY'), 'M', 'PINTOR', 1, 1, 5);
INSERT INTO CLIENTE (CLI_CODIGO, CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_TELEFONE, CLI_CELULAR, CLI_EMAIL, CLI_DATA_NASCIMENTO, CLI_SEXO, CLI_PROFISSAO, CLI_PAI_MAE, CLI_TIPC_CODIGO, CLI_END_CODIGO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'LUCIO', 'FLAVIO', '45687921352', '(47) 3033-6597', '(47) 98645-5236', 'LUCIO@GMAIL.COM', TO_DATE('02/11/1992', 'DD/MM/YYYY'), 'M', 'AUXILIAR ADMINISTRATIVO', 1, 1, 3);
INSERT INTO CLIENTE (CLI_CODIGO, CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_TELEFONE, CLI_CELULAR, CLI_EMAIL, CLI_DATA_NASCIMENTO, CLI_SEXO, CLI_PROFISSAO, CLI_PAI_MAE, CLI_TIPC_CODIGO, CLI_END_CODIGO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'MAURO', 'HENRIQUE', '52468713256', '(47) 3033-5623', '(47) 98645-5236', 'MAURO@GMAIL.COM', TO_DATE('02/11/1992', 'DD/MM/YYYY'), 'M', 'MONTADOR', 1, 1, 1);
INSERT INTO CLIENTE (CLI_CODIGO, CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_TELEFONE, CLI_CELULAR, CLI_EMAIL, CLI_DATA_NASCIMENTO, CLI_SEXO, CLI_PROFISSAO, CLI_PAI_MAE, CLI_TIPC_CODIGO, CLI_END_CODIGO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'JULIO', 'CESAR', '56893152468', '(47) 3033-2356', '(47) 98645-5236', 'JULIO@GMAIL.COM', TO_DATE('02/11/1992', 'DD/MM/YYYY'), 'M', 'PROFESSOR', 1, 1, 2);
INSERT INTO CLIENTE (CLI_CODIGO, CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_TELEFONE, CLI_CELULAR, CLI_EMAIL, CLI_DATA_NASCIMENTO, CLI_SEXO, CLI_PROFISSAO, CLI_PAI_MAE, CLI_TIPC_CODIGO, CLI_END_CODIGO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'LUKE', 'SKYWALKER', '65235142689', '(47) 3033-1345', '(47) 98645-5236', 'LUKE@GMAIL.COM', TO_DATE('02/11/1992', 'DD/MM/YYYY'), 'M', 'ADMINISTRADOR', 1, 1, 1);
INSERT INTO CLIENTE (CLI_CODIGO, CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_TELEFONE, CLI_CELULAR, CLI_EMAIL, CLI_DATA_NASCIMENTO, CLI_SEXO, CLI_PROFISSAO, CLI_PAI_MAE, CLI_TIPC_CODIGO, CLI_END_CODIGO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'ROBERTO', 'CARLOS', '41439856235', '(47) 3033-9764', '(47) 98645-5236', 'ROBERTO@GMAIL.COM', TO_DATE('02/11/1992', 'DD/MM/YYYY'), 'M', 'VENDEDOR', 1, 1, 2);
INSERT INTO CLIENTE (CLI_CODIGO, CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_TELEFONE, CLI_CELULAR, CLI_EMAIL, CLI_DATA_NASCIMENTO, CLI_SEXO, CLI_PROFISSAO, CLI_PAI_MAE, CLI_TIPC_CODIGO, CLI_END_CODIGO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'CESAR', 'AUGUSTO', '45678912352', '(47) 3033-4679', '(47) 98645-5236', 'CESAR@GMAIL.COM', TO_DATE('02/11/1992', 'DD/MM/YYYY'), 'M', 'SOLDADOR', 1, 1, 3);
INSERT INTO CLIENTE (CLI_CODIGO, CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_TELEFONE, CLI_CELULAR, CLI_EMAIL, CLI_DATA_NASCIMENTO, CLI_SEXO, CLI_PROFISSAO, CLI_PAI_MAE, CLI_TIPC_CODIGO, CLI_END_CODIGO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'MARIANA', 'OLIVEIRA', '65498732154', '(47) 3033-1346', '(47) 98645-5236', 'MARIANA@GMAIL.COM', TO_DATE('02/11/1992', 'DD/MM/YYYY'), 'F', 'PROFESSORA', 1, 1, 4);
INSERT INTO CLIENTE (CLI_CODIGO, CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_TELEFONE, CLI_CELULAR, CLI_EMAIL, CLI_DATA_NASCIMENTO, CLI_SEXO, CLI_PROFISSAO, CLI_PAI_MAE, CLI_TIPC_CODIGO, CLI_END_CODIGO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'ESTER', 'MARTINS', '45678945689', '(47) 3033-6598', '(47) 98645-5236', 'ESTER@GMAIL.COM', TO_DATE('02/11/1992', 'DD/MM/YYYY'), 'F', 'DONA DE CASA', 1, 1, 5);
INSERT INTO CLIENTE (CLI_CODIGO, CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_TELEFONE, CLI_CELULAR, CLI_EMAIL, CLI_DATA_NASCIMENTO, CLI_SEXO, CLI_PROFISSAO, CLI_PAI_MAE, CLI_TIPC_CODIGO, CLI_END_CODIGO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'FELIPE', 'GOMES', '59398732156', '(47) 3033-4578', '(47) 98645-5236', 'FELIPE@GMAIL.COM', TO_DATE('02/11/1992', 'DD/MM/YYYY'), 'M', 'VENDEDOR', 1, 1, 6);
INSERT INTO CLIENTE (CLI_CODIGO, CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_TELEFONE, CLI_CELULAR, CLI_EMAIL, CLI_DATA_NASCIMENTO, CLI_SEXO, CLI_PROFISSAO, CLI_PAI_MAE, CLI_TIPC_CODIGO, CLI_END_CODIGO)
VALUES (SEQ_CLIENTE.NEXTVAL, 'MARILENE', 'SOARES', '12365478965', '(47) 3033-2356', '(47) 98645-5236', 'MARILENE@GMAIL.COM', TO_DATE('02/11/1992', 'DD/MM/YYYY'), 'F', 'SECRETÁRIA', 1, 1, 7);

CREATE TABLE USUARIO_LOGIN (
USUL_CODIGO NUMBER(18) PRIMARY KEY,
USUL_LOGIN VARCHAR2(255) NOT NULL,
USUL_SENHA VARCHAR2(255) NOT NULL);

CREATE SEQUENCE SEQ_USUARIO_LOGIN
START WITH 1
INCREMENT BY 1;

INSERT INTO USUARIO_LOGIN (USUL_CODIGO, USUL_LOGIN, USUL_SENHA) VALUES (SEQ_USUARIO_LOGIN.NEXTVAL, 'ADMIN', '123');

CREATE TABLE TIPO_FUNCIONARIO (
TFUN_CODIGO NUMBER(18) PRIMARY KEY,
TFUN_NOME VARCHAR2(255) NOT NULL);

CREATE SEQUENCE SEQ_TIPO_FUNCIONARIO
START WITH 1
INCREMENT BY 1;

INSERT INTO TIPO_FUNCIONARIO (TFUN_CODIGO, TFUN_NOME) VALUES (SEQ_TIPO_FUNCIONARIO.NEXTVAL, 'ADMINISTRADOR');
INSERT INTO TIPO_FUNCIONARIO (TFUN_CODIGO, TFUN_NOME) VALUES (SEQ_TIPO_FUNCIONARIO.NEXTVAL, 'PADRÃO');

CREATE TABLE FUNCIONARIO (
FUN_CODIGO NUMBER(18) PRIMARY KEY,
FUN_NOME VARCHAR2(255) NOT NULL,
FUN_SOBRENOME VARCHAR2(255),
FUN_EMAIL VARCHAR2(255),
FUN_TELEFONE VARCHAR2(15),
FUN_TFUN_CODIGO NUMBER(18),
CONSTRAINT FK_TIPO_FUNCIONARIO FOREIGN KEY (FUN_TFUN_CODIGO) REFERENCES TIPO_FUNCIONARIO (TFUN_CODIGO));

CREATE SEQUENCE SEQ_FUNCIONARIO
START WITH 1
INCREMENT BY 1;

INSERT INTO FUNCIONARIO (FUN_CODIGO, FUN_NOME, FUN_SOBRENOME, FUN_EMAIL, FUN_TELEFONE, FUN_TFUN_CODIGO) VALUES
(SEQ_FUNCIONARIO.NEXTVAL, 'JOÃO', 'SILVA', 'JOAO@GMAIL.COM', '(47) 98954-2015', 1);
INSERT INTO FUNCIONARIO (FUN_CODIGO, FUN_NOME, FUN_SOBRENOME, FUN_EMAIL, FUN_TELEFONE, FUN_TFUN_CODIGO) VALUES
(SEQ_FUNCIONARIO.NEXTVAL, 'CARLOS', 'SANTOS', 'CARLOS@GMAIL.COM', '(47) 95689-2541', 2);

CREATE TABLE FABRICANTE (
FAB_CODIGO NUMBER(18) PRIMARY KEY,
FAB_NOME VARCHAR2(255) NOT NULL);

CREATE SEQUENCE SEQ_FABRICANTE
START WITH 1
INCREMENT BY 1;

INSERT INTO FABRICANTE (FAB_CODIGO, FAB_NOME) VALUES (SEQ_FABRICANTE.NEXTVAL, 'FABRICANTE A');
INSERT INTO FABRICANTE (FAB_CODIGO, FAB_NOME) VALUES (SEQ_FABRICANTE.NEXTVAL, 'FABRICANTE B');

CREATE TABLE FAMILIA (
FAM_CODIGO NUMBER(18) PRIMARY KEY,
FAM_NOME VARCHAR2(255) NOT NULL);

CREATE SEQUENCE SEQ_FAMILIA
START WITH 1
INCREMENT BY 1;

INSERT INTO FAMILIA (FAM_CODIGO, FAM_NOME) VALUES (SEQ_FAMILIA.NEXTVAL, 'FAMILIA A');
INSERT INTO FAMILIA (FAM_CODIGO, FAM_NOME) VALUES (SEQ_FAMILIA.NEXTVAL, 'FAMILIA B');
INSERT INTO FAMILIA (FAM_CODIGO, FAM_NOME) VALUES (SEQ_FAMILIA.NEXTVAL, 'FAMILIA C');

CREATE TABLE LISTA_DE_PRECO (
LP_CODIGO NUMBER(18) PRIMARY KEY,
LP_NOME VARCHAR2(45) NOT NULL,
LP_FATOR NUMBER(18,2));

CREATE SEQUENCE SEQ_LISTA_DE_PRECO
START WITH 1
INCREMENT BY 1;

CREATE TABLE DEPOSITO (
DEP_CODIGO NUMBER(18) PRIMARY KEY,
DEP_NOME VARCHAR2(255) NOT NULL);

CREATE SEQUENCE SEQ_DEPOSITO
START WITH 1
INCREMENT BY 1;

CREATE TABLE PRODUTO (
PRO_CODIGO NUMBER(18) PRIMARY KEY,
PRO_DESCRICAO VARCHAR2(255),
PRO_PRECO NUMBER(18,2),
PRO_NOME_UNIDADE_COMPRA VARCHAR2(255),
PRO_POR_UNIDADE_COMPRA NUMBER(18,2),
PRO_QTDE_POR_COMPRA NUMBER(18,2),
PRO_NOME_UNIDADE_VENDA VARCHAR2(255),
PRO_POR_UNIDADE_VENDA NUMBER(18,2),
PRO_QTDE_POR_VENDA NUMBER(18,2),
PRO_ESTOQUE_MIN NUMBER(18),
PRO_ESTOQUE_MAX NUMBER(18),
PRO_ATIVO NUMBER(1),
PRO_OBSERVACAO VARCHAR2(255),
PRO_ANEXO VARCHAR2(255),
PRO_FAM_CODIGO NUMBER(18),
PRO_FAB_CODIGO NUMBER(18),
PRO_LP_CODIGO NUMBER(18),
PRO_DEP_CODIGO NUMBER(18),
CONSTRAINT FK_FAMILIA_PRODUTO FOREIGN KEY (PRO_FAM_CODIGO) REFERENCES FAMILIA (FAM_CODIGO),
CONSTRAINT FK_FABRICANTE_PRODUTO FOREIGN KEY (PRO_FAB_CODIGO) REFERENCES FABRICANTE (FAB_CODIGO),
CONSTRAINT FK_PRODUTO_LISTA FOREIGN KEY (PRO_LP_CODIGO) REFERENCES LISTA_DE_PRECO (LP_CODIGO),
CONSTRAINT FK_PRODUTO_DEPOSITO FOREIGN KEY (PRO_DEP_CODIGO) REFERENCES DEPOSITO (DEP_CODIGO));

CREATE SEQUENCE SEQ_PRODUTO
START WITH 1
INCREMENT BY 1;

INSERT INTO PRODUTO (PRO_CODIGO, PRO_DESCRICAO, PRO_ESTOQUE_MIN, PRO_ESTOQUE_MAX, PRO_ATIVO, PRO_FAM_CODIGO, PRO_FAB_CODIGO)
VALUES (SEQ_PRODUTO.NEXTVAL, 'SHAMPOO', 5, 100, 1, 1, 1);
INSERT INTO PRODUTO (PRO_CODIGO, PRO_DESCRICAO, PRO_ESTOQUE_MIN, PRO_ESTOQUE_MAX, PRO_ATIVO, PRO_FAM_CODIGO, PRO_FAB_CODIGO)
VALUES (SEQ_PRODUTO.NEXTVAL, 'CONDICIONADOR', 5, 100, 1, 2, 1);
INSERT INTO PRODUTO (PRO_CODIGO, PRO_DESCRICAO, PRO_ESTOQUE_MIN, PRO_ESTOQUE_MAX, PRO_ATIVO, PRO_FAM_CODIGO, PRO_FAB_CODIGO)
VALUES (SEQ_PRODUTO.NEXTVAL, 'TONALIZANTE', 5, 100, 1, 3, 2);

CREATE TABLE SERVICO (
SER_CODIGO NUMBER(18) PRIMARY KEY,
SER_NOME VARCHAR2(255) NOT NULL,
SER_PRECO NUMBER(18,2),
SER_ATIVO NUMBER(1),
SER_NOME_UNIDADE_COMPRA VARCHAR2(255),
SER_POR_UNIDADE_COMPRA NUMBER(18,2),
SER_QTDE_POR_COMPRA NUMBER(18,2),
SER_NOME_UNIDADE_VENDA VARCHAR2(255),
SER_POR_UNIDADE_VENDA NUMBER(18,2),
SER_QTDE_POR_VENDA NUMBER(18,2),
SER_OBSERVACAO VARCHAR2(255),
SER_ANEXO VARCHAR2(255),
SER_FAM_CODIGO NUMBER(18),
SER_LP_CODIGO NUMBER(18),
CONSTRAINT FK_FAMILIA_SERVICO FOREIGN KEY (SER_FAM_CODIGO) REFERENCES FAMILIA (FAM_CODIGO),
CONSTRAINT FK_SERVICO_LISTA FOREIGN KEY (SER_LP_CODIGO) REFERENCES LISTA_DE_PRECO (LP_CODIGO));

CREATE SEQUENCE SEQ_SERVICO
START WITH 1
INCREMENT BY 1;

INSERT INTO SERVICO (SER_CODIGO, SER_NOME, SER_ATIVO, SER_FAM_CODIGO) VALUES (SEQ_SERVICO.NEXTVAL, 'CORTE DE CABELO MASCULINO', 1, 1);
INSERT INTO SERVICO (SER_CODIGO, SER_NOME, SER_ATIVO, SER_FAM_CODIGO) VALUES (SEQ_SERVICO.NEXTVAL, 'CORTE DE CABELO FEMININO', 1, 2);
INSERT INTO SERVICO (SER_CODIGO, SER_NOME, SER_ATIVO, SER_FAM_CODIGO) VALUES (SEQ_SERVICO.NEXTVAL, 'ALISAMENTO', 1, 3);

CREATE TABLE SERVICO_PRODUTO (
SP_CODIGO NUMBER(18) PRIMARY KEY,
SP_SER_CODIGO NUMBER(18) NOT NULL,
SP_PRO_CODIGO NUMBER(18),
CONSTRAINT FK_SP_SERVICO FOREIGN KEY (SP_SER_CODIGO) REFERENCES SERVICO (SER_CODIGO),
CONSTRAINT FK_SP_PRODUTO FOREIGN KEY (SP_PRO_CODIGO) REFERENCES PRODUTO (PRO_CODIGO));

CREATE SEQUENCE SEQ_SERVICO_PRODUTO
START WITH 1
INCREMENT BY 1;

INSERT INTO SERVICO_PRODUTO (SP_CODIGO, SP_SER_CODIGO, SP_PRO_CODIGO) VALUES (SEQ_SERVICO_PRODUTO.NEXTVAL, 1, 1);
INSERT INTO SERVICO_PRODUTO (SP_CODIGO, SP_SER_CODIGO, SP_PRO_CODIGO) VALUES (SEQ_SERVICO_PRODUTO.NEXTVAL, 2, 1);
INSERT INTO SERVICO_PRODUTO (SP_CODIGO, SP_SER_CODIGO, SP_PRO_CODIGO) VALUES (SEQ_SERVICO_PRODUTO.NEXTVAL, 2, 2);
INSERT INTO SERVICO_PRODUTO (SP_CODIGO, SP_SER_CODIGO, SP_PRO_CODIGO) VALUES (SEQ_SERVICO_PRODUTO.NEXTVAL, 3, 3);


CREATE TABLE AGENDA (
AG_CODIGO NUMBER(18) PRIMARY KEY,
AG_OBSERVACAO VARCHAR2(255),
AG_DATA_SISTEMA DATE NOT NULL,
AG_DATA_INICIO DATE NOT NULL,
AG_DATA_TERMINO DATE NOT NULL,
AG_HORA_INICIO TIMESTAMP NOT NULL,
AG_HORA_TERMINO TIMESTAMP NOT NULL,
AG_LEMBRETE VARCHAR2(45),
AG_AVISO VARCHAR2(45),
AG_ATIVO NUMBER(1),
AG_FECHADO NUMBER(1));

CREATE SEQUENCE SEQ_AGENDA
START WITH 1
INCREMENT BY 1;

CREATE TABLE SALVA_AGENDA (
SAL_CODIGO NUMBER(18) PRIMARY KEY,
SAL_AG_CODIGO NUMBER(18) NOT NULL,
SAL_CLI_CODIGO NUMBER(18) NOT NULL,
SAL_FUN_CODIGO NUMBER(18) NOT NULL,
SAL_SP_CODIGO NUMBER (18) NOT NULL,
CONSTRAINT FK_SALVA_AGENDA FOREIGN KEY (SAL_AG_CODIGO) REFERENCES AGENDA (AG_CODIGO),
CONSTRAINT FK_SALVA_CLIENTE FOREIGN KEY (SAL_CLI_CODIGO) REFERENCES CLIENTE (CLI_CODIGO),
CONSTRAINT FK_SALVA_FUNCIONARIO FOREIGN KEY (SAL_FUN_CODIGO) REFERENCES FUNCIONARIO (FUN_CODIGO),
CONSTRAINT FK_SALVA_SP FOREIGN KEY (SAL_SP_CODIGO) REFERENCES SERVICO_PRODUTO (SP_CODIGO));

CREATE SEQUENCE SEQ_SALVA_AGENDA
START WITH 1
INCREMENT BY 1;


CREATE TABLE FORMA_PAGAMENTO (
FORMA_CODIGO NUMBER(18) PRIMARY KEY,
FORMA_NOME VARCHAR2(255) NOT NULL);

CREATE SEQUENCE SEQ_FORMA_PAGAMENTO
START WITH 1
INCREMENT BY 1;

CREATE TABLE CAIXA (
CX_CODIGO NUMBER(18) PRIMARY KEY,
CX_SAL_CODIGO NUMBER(18) NOT NULL,
CX_FORMA_CODIGO NUMBER(18) NOT NULL,
CONSTRAINT FK_CAIXA_SALVA_AGENDA FOREIGN KEY (CX_SAL_CODIGO) REFERENCES SALVA_AGENDA (SAL_CODIGO),
CONSTRAINT FK_CAIXA_FORMA FOREIGN KEY (CX_FORMA_CODIGO) REFERENCES FORMA_PAGAMENTO (FORMA_CODIGO));

CREATE SEQUENCE SEQ_CAIXA
START WITH 1
INCREMENT BY 1;

CREATE TABLE CONTAS_RECEBER (
CAR_CODIGO NUMBER(18) PRIMARY KEY,
CAR_DATA_LANCAMENTO DATE NOT NULL,
CAR_DIAS_DE_ATRASO NUMBER(18),
CAR_SALDO NUMBER(18,2),
CAR_DESCONTO NUMBER(18,2),
CAR_PAGAMENTO_TOTAL NUMBER(18,2),
CAR_CX_CODIGO NUMBER(18),
CONSTRAINT FK_CAR_CAIXA FOREIGN KEY (CAR_CX_CODIGO) REFERENCES CAIXA (CX_CODIGO));

CREATE SEQUENCE SEQ_CONTAS_RECEBER
START WITH 1
INCREMENT BY 1;

CREATE TABLE NOTA_DE_COMPRA (
NTC_CODIGO NUMBER(18) PRIMARY KEY,
NTC_QTDE NUMBER(18) NOT NULL,
NTC_PRECO_ITEM NUMBER(18,2) NOT NULL,
NTC_VALOR_TOTAL NUMBER(18,2) NOT NULL,
NTC_DATA_LANCAMENTO DATE NOT NULL,
NTC_OBSERVACAO VARCHAR2(255),
NTC_ANEXO VARCHAR2(255),
NTC_NUMERO_NOTA VARCHAR2(255),
NTC_DESCONTO NUMBER(18,2),
NTC_FOR_CODIGO NUMBER(18),
NTC_PRO_CODIGO NUMBER(18),
NTC_FORMA_CODIGO NUMBER(18),
CONSTRAINT FK_NOTA_FORNECEDOR FOREIGN KEY (NTC_FOR_CODIGO) REFERENCES FORNECEDOR (FOR_CODIGO),
CONSTRAINT FK_NOTA_PRODUTO FOREIGN KEY (NTC_PRO_CODIGO) REFERENCES PRODUTO (PRO_CODIGO),
CONSTRAINT FK_NOTA_FORMA FOREIGN KEY (NTC_FORMA_CODIGO) REFERENCES FORMA_PAGAMENTO (FORMA_CODIGO));

CREATE SEQUENCE SEQ_NOTA
START WITH 1
INCREMENT BY 1;

CREATE TABLE CONTAS_A_PAGAR (
CAP_CODIGO NUMBER(18) PRIMARY KEY,
CAP_DIAS_ATRASO NUMBER(18),
CAP_SALDO NUMBER(18,2),
CAP_VALOR_TOTAL NUMBER(18,2) NOT NULL,
CAP_DATA_LANCAMENTO DATE NOT NULL,
CAP_PAGAMENTO_TOTAL NUMBER(18,2),
CAP_DESCONTO NUMBER(18,2),
CAP_FOR_CODIGO NUMBER(18),
CAP_FORMA_CODIGO NUMBER(18),
CONSTRAINT FK_CAP_FORNECEDOR FOREIGN KEY (CAP_FOR_CODIGO) REFERENCES FORNECEDOR (FOR_CODIGO),
CONSTRAINT FK_CAP_FORMA FOREIGN KEY (CAP_FORMA_CODIGO) REFERENCES FORMA_PAGAMENTO (FORMA_CODIGO));


CREATE SEQUENCE SEQ_CAP
START WITH 1
INCREMENT BY 1;

CREATE TABLE LANCAMENTO_CONTABIL (
LC_CODIGO NUMBER(18) PRIMARY KEY,
LC_DATA_LANCAMENTO DATE NOT NULL,
LC_OBSERVACAO VARCHAR2(255),
LC_CAP_CODIGO NUMBER(18),
LC_CAR_CODIGO NUMBER(18),
CONSTRAINT FK_LC_CAP FOREIGN KEY (LC_CAP_CODIGO) REFERENCES CONTAS_A_PAGAR (CAP_CODIGO),
CONSTRAINT FK_LC_CAR FOREIGN KEY (LC_CAR_CODIGO) REFERENCES CONTAS_RECEBER (CAR_CODIGO));

CREATE SEQUENCE SEQ_LC
START WITH 1
INCREMENT BY 1;

CREATE TABLE PLANO_DE_CONTAS (
CONTA_CODIGO NUMBER(18) PRIMARY KEY,
CONTA_NOME VARCHAR2(255) NOT NULL,
CONTA_SALDO NUMBER(18),
CONTA_CAIXA VARCHAR2(255),
CONTA_ATIVA NUMBER(1),
CONTA_CONFIDENCIAL NUMBER(1),
CONTA_CENTRO_DE_CUSTO VARCHAR2(255),
CONTA_CODIGO_EXTERNO NUMBER(18));

CREATE SEQUENCE SEQ_CONTA
START WITH 1
INCREMENT BY 1;

CREATE TABLE LANCAMENTO_CONTABIL_LINHAS	 (
LCL_CODIGO NUMBER(18) PRIMARY KEY,
LCL_DEBITO NUMBER(18),
LCL_CREDITO NUMBER(18),
LCL_DATA_VENCIMENTO DATE,
LCL_OBSERVACAO VARCHAR2(255),
LCL_LC_CODIGO NUMBER(18),
LCL_CONTA_CODIGO NUMBER(18),
CONSTRAINT FK_LCL_LC FOREIGN KEY (LCL_LC_CODIGO) REFERENCES LANCAMENTO_CONTABIL (LC_CODIGO),
CONSTRAINT FK_LCL_CONTA FOREIGN KEY (LCL_CONTA_CODIGO) REFERENCES PLANO_DE_CONTAS (CONTA_CODIGO));


CREATE SEQUENCE SEQ_LCL
START WITH 1
INCREMENT BY 1;